[package]
name = "safecoin-config-program"
version = "1.6.19"
description = "Panoptis Config program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-config-program"
edition = "2018"

[dependencies]
bincode = "1.3.1"
chrono = { version = "0.4.11", features = ["serde"] }
log = "0.4.11"
rand_core = "0.6.2"
serde = "1.0.122"
serde_derive = "1.0.103"
safecoin-sdk = { path = "../../sdk", version = "=1.6.19" }

[dev-dependencies]
safecoin-logger = { path = "../../logger", version = "=1.6.19" }

[lib]
crate-type = ["lib"]
name = "solana_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
