[package]
name = "panoptis-sdk-macro"
version = "1.6.19"
description = "Panoptis SDK Macro"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/panoptisdev/panoptis"
homepage = "https://panoptis.network/"
documentation = "https://docs.rs/panoptis-sdk-macro"
license = "Apache-2.0"
edition = "2018"

[lib]
name = "solana_sdk_macro"
proc-macro = true

[dependencies]
bs58 = "0.3.0"
proc-macro2 = "1.0.19"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
rustversion = "1.0.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
