[package]
name = "panoptis-cargo-build-bpf"
version = "1.6.19"
description = "Compile a local package and all of its dependencies using the Panoptis BPF SDK"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
homepage = "https://safecoin.org/"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
bzip2 = "0.3.3"
clap = "2.33.3"
cargo_metadata = "0.12.0"
panoptis-download-utils = { path = "../../download-utils", version = "=1.6.19" }
panoptis-sdk = { path = "..", version = "=1.6.19" }
tar = "0.4.28"

[features]
program = []

[[bin]]
name = "cargo-build-bpf"
path = "src/main.rs"
