[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "panoptis-remote-wallet"
description = "Panoptis: Enterprise Security for the Community by the Community"
version = "1.6.19"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://panoptis.network/"
documentation = "https://docs.rs/panoptis-remote-wallet"

[dependencies]
base32 = "0.4.0"
console = "0.11.3"
dialoguer = "0.6.2"
hidapi = { version = "1.2.5", default-features = false }
log = "0.4.11"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
parking_lot = "0.10"
qstring = "0.7.2"
semver = "0.9"
panoptis-sdk = { path = "../sdk", version = "=1.6.19" }
thiserror = "1.0"
uriparse = "0.6.3"

[features]
default = ["linux-static-hidraw"]
linux-static-libusb = ["hidapi/linux-static-libusb"]
linux-static-hidraw = ["hidapi/linux-static-hidraw"]
linux-shared-libusb = ["hidapi/linux-shared-libusb"]
linux-shared-hidraw = ["hidapi/linux-shared-hidraw"]

[[bin]]
name = "panoptis-ledger-udev"
path = "src/bin/ledger-udev.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
