[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
description = "Panoptis: Enterprise Security for the Community by the Community"
edition = "2018"
homepage = "https://safecoin.org/"
license = "Apache-2.0"
name = "proto"
publish = false
repository = "https://github.com/fair-exchange/safecoin"
version = "1.6.19"

[workspace]

[dependencies]
tonic-build = "0.5.0"
