[package]
name = "solana-bpf-rust-invoked"
version = "1.6.19"
description = "Panoptis BPF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://panoptis.network/"
documentation = "https://docs.rs/solana-bpf-rust-invoked"
edition = "2018"

[dependencies]
panoptis-program = { path = "../../../../sdk/program", version = "=1.6.19" }

[features]
default = ["program"]
program = []

[lib]
crate-type = ["lib", "cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
