[package]
name = "panoptis-program"
version = "1.6.19"
description = "Panoptis Program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/panoptisdev/panoptis"
homepage = "https://panoptis.network/"
documentation = "https://docs.rs/panoptis-program"
license = "Apache-2.0"
edition = "2018"

[lib]
name = "solana_program"

[dependencies]
bincode = "1.3.1"
borsh = "0.9.0"
borsh-derive = "0.9.0"
bs58 = "0.3.1"
bv = { version = "0.11.1", features = ["serde"] }
hex = "0.4.2"
itertools =  "0.9.0"
lazy_static = "1.4.0"
log = "0.4.8"
num-derive = "0.3"
num-traits = "0.2"
rustversion = "1.0.3"
serde = "1.0.112"
serde_bytes = "0.11"
serde_derive = "1.0.103"
sha2 = "0.9.2"
sha3 = "0.9.1"
panoptis-frozen-abi = { path = "../../frozen-abi", version = "=1.6.19" }
panoptis-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "=1.6.19" }
panoptis-sdk-macro = { path = "../macro", version = "=1.6.19" }
thiserror = "1.0"

[target.'cfg(not(target_arch = "bpf"))'.dependencies]
blake3 = "0.3.7"
curve25519-dalek = "2.1.0"
rand = "0.7.0"
panoptis-logger = { path = "../../logger", version = "=1.6.19" }

[dev-dependencies]
assert_matches = "1.3.0"
bincode = "1.3.1"
serde_json = "1.0.56"

[build-dependencies]
rustc_version = "0.2"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
