[package]
name = "panoptis-merkle-tree"
version = "1.6.19"
description = "Panoptis Merkle Tree"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/panoptisdev/panoptis"
license = "Apache-2.0"
homepage = "https://panoptis.network/"
documentation = "https://docs.rs/panoptis-merkle-tree"
edition = "2018"

[dependencies]
panoptis-program = { path = "../sdk/program", version = "=1.6.19" }
fast-math = "0.1"

# This can go once the BPF toolchain target Rust 1.42.0+
[target.bpfel-unknown-unknown.dependencies]
matches = "0.1.8"

[dev-dependencies]
hex = "0.4.2"

[lib]
crate-type = ["lib"]
name = "solana_merkle_tree"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
