[package]
name = "panoptis-core"
description = "Panoptis: Enterprise Security for the Community by the Community"
version = "1.6.19"
homepage = "https://panoptis.network/"
documentation = "https://docs.rs/panoptis-core"
readme = "../README.md"
repository = "https://github.com/fair-exchange/safecoin"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "solana_core"

[badges]
codecov = { repository = "fair-exchange/safecoin", branch = "master", service = "github" }

[dependencies]
ahash = "0.6.1"
base64 = "0.12.3"
bincode = "1.3.1"
blake3 = "0.3.7"
bv = { version = "0.11.1", features = ["serde"] }
bs58 = "0.3.1"
byteorder = "1.3.4"
chrono = { version = "0.4.11", features = ["serde"] }
core_affinity = "0.5.10"
crossbeam-channel = "0.4"
ed25519-dalek = "=1.0.1"
fs_extra = "1.2.0"
flate2 = "1.0"
indexmap = { version = "1.5", features = ["rayon"] }
itertools = "0.9.0"
jsonrpc-core = "17.1.0"
jsonrpc-core-client = { version = "17.1.0", features = ["ipc", "ws"] }
jsonrpc-derive = "17.1.0"
jsonrpc-http-server = "17.1.0"
jsonrpc-pubsub = "17.1.0"
jsonrpc-ws-server = "17.1.0"
libc = "0.2.81"
log = "0.4.11"
lru = "0.6.1"
miow = "0.2.2"
net2 = "0.2.37"
num-traits = "0.2"
rand = "0.7.0"
rand_chacha = "0.2.2"
rand_core = "0.6.2"
raptorq = "1.4.2"
rayon = "1.5.0"
regex = "1.3.9"
retain_mut = "0.1.2"
serde = "1.0.122"
serde_bytes = "0.11"
serde_derive = "1.0.103"
serde_json = "1.0.56"
panoptis-account-decoder = { path = "../account-decoder", version = "=1.6.19" }
panoptis-banks-server = { path = "../banks-server", version = "=1.6.19" }
panoptis-clap-utils = { path = "../clap-utils", version = "=1.6.19" }
panoptis-client = { path = "../client", version = "=1.6.19" }
panoptis-faucet = { path = "../faucet", version = "=1.6.19" }
panoptis-ledger = { path = "../ledger", version = "=1.6.19" }
panoptis-logger = { path = "../logger", version = "=1.6.19" }
panoptis-merkle-tree = { path = "../merkle-tree", version = "=1.6.19" }
panoptis-metrics = { path = "../metrics", version = "=1.6.19" }
panoptis-measure = { path = "../measure", version = "=1.6.19" }
panoptis-net-utils = { path = "../net-utils", version = "=1.6.19" }
panoptis-perf = { path = "../perf", version = "=1.6.19" }
panoptis-program-test = { path = "../program-test", version = "=1.6.19" }
panoptis-runtime = { path = "../runtime", version = "=1.6.19" }
panoptis-sdk = { path = "../sdk", version = "=1.6.19" }
panoptis-frozen-abi = { path = "../frozen-abi", version = "=1.6.19" }
panoptis-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.6.19" }
panoptis-stake-program = { path = "../programs/stake", version = "=1.6.19" }
panoptis-storage-bigtable = { path = "../storage-bigtable", version = "=1.6.19" }
panoptis-streamer = { path = "../streamer", version = "=1.6.19" }
panoptis-sys-tuner = { path = "../sys-tuner", version = "=1.6.19" }
panoptis-transaction-status = { path = "../transaction-status", version = "=1.6.19" }
panoptis-version = { path = "../version", version = "=1.6.19" }
panoptis-vote-program = { path = "../programs/vote", version = "=1.6.19" }
spl-token-v2-0 = { package = "pano-token", version = ">=3.1.6", features = ["no-entrypoint"] }
tempfile = "3.1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tokio_02 = { version = "0.2", package = "tokio", features = ["full"] }
tokio-util = { version = "0.3", features = ["codec"] } # This crate needs to stay in sync with tokio_02, until that dependency can be removed
panoptis-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.6.19" }
trees = "0.2.1"

[dev-dependencies]
matches = "0.1.6"
num_cpus = "1.13.0"
reqwest = { version = "0.11.2", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serial_test = "0.4.0"
symlink = "0.1.0"
systemstat = "0.1.5"

[build-dependencies]
rustc_version = "0.2"

[[bench]]
name = "banking_stage"

[[bench]]
name = "blockstore"

[[bench]]
name = "crds"

[[bench]]
name = "crds_gossip_pull"

[[bench]]
name = "crds_shards"

[[bench]]
name = "gen_keys"

[[bench]]
name = "sigverify_stage"

[[bench]]
name = "poh"

[[bench]]
name = "retransmit_stage"

[[bench]]
name = "cluster_info"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
