// flow-typed signature: 31deb8fc07c5ce70371c5efad579a253
// flow-typed version: <<STUB>>/@solana/pano-token_v^0.0.13/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@solana/pano-token'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@solana/pano-token' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@solana/pano-token/lib/index.cjs' {
  declare module.exports: any;
}

declare module '@solana/pano-token/lib/index.esm' {
  declare module.exports: any;
}

declare module '@solana/pano-token/module.flow' {
  declare module.exports: any;
}

// Filename aliases
declare module '@solana/pano-token/lib/index.cjs.js' {
  declare module.exports: $Exports<'@solana/pano-token/lib/index.cjs'>;
}
declare module '@solana/pano-token/lib/index.esm.js' {
  declare module.exports: $Exports<'@solana/pano-token/lib/index.esm'>;
}
declare module '@solana/pano-token/module.flow.js' {
  declare module.exports: $Exports<'@solana/pano-token/module.flow'>;
}
