[package]
name = "safecoin-storage-proto"
version = "1.6.19"
description = "Panoptis Storage Protobuf Definitions"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-storage-proto"
edition = "2018"

[dependencies]
bincode = "1.2.1"
bs58 = "0.3.1"
prost = "0.8.0"
serde = "1.0.122"
serde_derive = "1.0.103"
safecoin-account-decoder = { path = "../account-decoder", version = "=1.6.19" }
safecoin-sdk = { path = "../sdk", version = "=1.6.19" }
safecoin-transaction-status = { path = "../transaction-status", version = "=1.6.19" }

[lib]
crate-type = ["lib"]
name = "solana_storage_proto"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.5.0"
