[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "panoptis-store-tool"
description = "Tool to inspect append vecs"
version = "1.6.19"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
publish = false

[dependencies]
log = { version = "0.4.11" }
panoptis-logger = { path = "../../logger", version = "=1.6.19" }
panoptis-version = { path = "../../version", version = "=1.6.19" }
panoptis-measure = { path = "../../measure", version = "=1.6.19" }
panoptis-runtime = { path = "..", version = "=1.6.19" }
panoptis-sdk = { path = "../../sdk", version = "=1.6.19" }
clap = "2.33.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
