[package]
name = "panoptis-vote-program"
version = "1.6.19"
description = "Panoptis Vote program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/panoptisdev/panoptis"
license = "Apache-2.0"
homepage = "https://panoptis.network/"
documentation = "https://docs.rs/panoptis-vote-program"
edition = "2018"

[dependencies]
bincode = "1.3.1"
log = "0.4.11"
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.122"
serde_derive = "1.0.103"
panoptis-frozen-abi = { path = "../../frozen-abi", version = "=1.6.19" }
panoptis-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "=1.6.19" }
panoptis-logger = { path = "../../logger", version = "=1.6.19" }
panoptis-metrics = { path = "../../metrics", version = "=1.6.19" }
panoptis-sdk = { path = "../../sdk", version = "=1.6.19" }
thiserror = "1.0"

[build-dependencies]
rustc_version = "0.2"
chrono = "0.4.19"

[lib]
crate-type = ["lib"]
name = "solana_vote_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
