[package]
name = "panoptis-metrics"
version = "1.6.19"
description = "Panoptis Metrics"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://panoptis.network/"
documentation = "https://docs.rs/panoptis-metrics"
edition = "2018"

[dependencies]
env_logger = "0.8.3"
gethostname = "0.2.1"
lazy_static = "1.4.0"
log = "0.4.11"
reqwest = { version = "0.11.2", default-features = false, features = ["blocking", "rustls-tls", "json"] }
panoptis-sdk = { path = "../sdk", version = "=1.6.19" }

[dev-dependencies]
rand = "0.7.0"
serial_test = "0.4.0"

[lib]
name = "solana_metrics"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
